[config]
quick_exec=1

[desktop]
wallpaper_mode=color
wallpaper=
desktop_bg=#2e3440
show_documents=0
show_trash=0
show_mounts=0

[volume]
mount_on_startup=1
mount_removable=1

[ui]
desktop_double_click=1
icon_size=48
