.TH QUADRF-APPLY-WIFI 8 "August 2026" "QuadRF" "QuadRF"
.SH NAME
quadrf-apply-wifi \- save a client Wi-Fi network
.SH SYNOPSIS
.B quadrf-apply-wifi
.I ssid
.RI [ passphrase ]
.SH DESCRIPTION
Replaces
.I /etc/wpa_supplicant/wpa_supplicant.conf
with a single network for
.IR ssid ,
using
.I passphrase
for WPA or an open network when none is given.
.PP
This does not change client versus hotspot mode and does not reboot. The
control panel saves credentials here, then
.B quadrf-hotspot sta
joins when the operator turns Client on.
.PP
Any previously configured network is discarded. If the saved network does
not associate,
.BR quadrf-hotspot (8)
starts the fallback access point when
.B QUADRF_WIFI_FALLBACK
is yes.
.SH SEE ALSO
.BR quadrf (1),
.BR quadrf-hotspot (8),
.BR wpa_supplicant.conf (5)
